stages:
    - test
    - post

include:
    - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v5/test.yml'

test:v1.0:
  extends: .test
  variables:
      CI_IMAGE_TAG: 'rocm'
      CI_VERSION_TAG: 'v1.0'
  tags:
      - rocm

test:v1.1:
  extends: .test
  variables:
      CI_IMAGE_TAG: 'rocm'
      CI_VERSION_TAG: 'v1.1'
  tags:
      - rocm

test:v1.2:
  extends: .test
  variables:
      CI_IMAGE_TAG: 'rocm'
      CI_VERSION_TAG: 'v1.2'
  tags:
      - rocm

test:v1.3:
  extends: .test
  variables:
      CI_IMAGE_TAG: 'rocm'
      CI_VERSION_TAG: 'v1.3'
  tags:
      - rocm

test:dev:
  extends: .test
  variables:
      CI_IMAGE_TAG: 'rocm'
      CI_VERSION_TAG: 'dev'
  tags:
      - rocm
  allow_failure: true
